#!/bin/bash

echo "Hello World! I am a homosapian!"
if [[ "$#" -eq 1 ]]
then {
	echo "Is your name $1? [y/n]"
	read R
	if [[ "$R" = "y" ]]
	then
		echo "Welcome $1!"
	elif [[ "$R" = "n" ]]
	then
		echo "Well.. enter your name"
	else
		echo "incorrect input"
	fi
}
else
	echo "Must be 1 input which is your name"
fi

