#!/bin/bash

if [[ "$#" -eq 2 ]]
then {
	if [[ -f "$1" ]]
	then {
		grep -w "$2$" $1
		echo " "
		echo "Good bye!" 
	}
	else 
		echo "File not found!, please ensure the file name is spelt correctly."	
	fi
}
else {
	echo "You need to provide two arguments for this script to work."
	echo "Usage: my-lookup <file-name> <lastname>"
}
fi
